name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.18.0
  firebase_auth: ^4.11.0
  cloud_firestore: 4.10.0
  firebase_storage: 11.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

